---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: containergroup-sa
  namespace: ansible-automation-platform
# oc sa get-token containergroup-sa
...
