---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: containergroup-role-binding
  namespace: ansible-automation-platform
subjects:
- kind: ServiceAccount
  name: containergroup-sa
  namespace: ansible-automation-platform
roleRef:
  kind: Role
  name: containergroup-role
  apiGroup: rbac.authorization.k8s.io
...
