---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: ansible-automation-platform-operator
  namespace: ansible-automation-platform
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  targetNamespaces:
    - ansible-automation-platform
...
