---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: gitlab-runner-operator
#  namespace: testathon-gitlab-runner
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitlab-runner-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
...
